# Generated by Django 3.2.12 on 2022-03-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_orders_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_foodlist',
            new_name='Orderfood',
        ),
    ]
